<?php

/**
 * @file
 * Contains comic_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Render\Element;

/**
 * Implements hook_help().
 */
function pbs_media_manager_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pbs_media_manager module.
    case 'help.page.pbs_media_manager':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('PBS Media Manager') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function pbs_media_manager_theme($existing, $type, $theme, $path) {
  return [
    'pbs_mm_show' => [
      'render element' => 'elements',
    ],
    'pbs_mm_asset' => [
      'render element' => 'elements',
    ],
    'pbs_mm_asset_teasers' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for show templates.
 */
function template_preprocess_pbs_mm_show(&$variables) {
  // Helpful $content variable for templates.
  $variables['content'] = [];
  foreach ($variables['elements']['#show'] as $key => $value) {
    $variables['content'][$key] = $variables['elements']['#show'][$key];
  }
}

/**
 * Prepares variables for asset templates.
 */
function template_preprocess_pbs_mm_asset(&$variables) {
  // Helpful $content variable for templates.
  $variables['content'] = [];
  foreach ($variables['elements']['#asset'] as $key => $value) {
    $variables['content'][$key] = $variables['elements']['#asset'][$key];
  }
}


/**
 * Prepares variables for asset teaser templates.
 */
function template_preprocess_pbs_mm_asset_teasers(&$variables) {
  // Helpful $content variable for templates.
  $variables['content'] = [];
  foreach ($variables['elements']['#asset_teasers'] as $i => $asset) {
    foreach ($asset as $key => $value) {
      $variables['content'][$i][$key] = $value;
    }
    
  }
}